## Singular Value Decomposition



In [4]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print(A)
print("\n")

U, s, VT = svd(A)
print(U)
print("\n")
print(s)
print("\n")
print(VT)

[[1 2]
 [3 4]
 [5 6]]


[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


[9.52551809 0.51430058]


[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## LUP Decomposition

The LU decomposition is for square matrices and decomposes a matrix into L and U components. The factors L and U are triangular matrices. The factorization that comes from elimination is A = LU. A variation of this decomposition that is numerically more stable to solve in practice is called the LUP decomposition, or the LU decomposition with partial pivoting. The rows of the parent matrix are re-ordered to simplify the decomposition process and the additional P matrix specifies a way to permute the result or return the result to the original order.

In [9]:
# LU decomposition
from numpy import array
from scipy.linalg import lu

A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print("\n")

P, L, U = lu(A)

print(P)
print("\n")
print(L)
print("\n")
print(U)
print("\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]




## QR Decomposition


In [10]:
# QR decomposition
from numpy import array
from numpy.linalg import qr

A = array([[1, 2], [3, 4], [5, 6]])
print(A)
print("\n")

Q, R = qr(A, 'complete')
print(Q)
print("\n")
print(R)
print("\n")

[[1 2]
 [3 4]
 [5 6]]


[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


